/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visao;

import DAO.BuscarDAO;
import Modelo.Registro_fornecedor;
import Modelo.Registro_produto;
import Modelo.Registro_usuario;
import java.util.ArrayList;
import javax.swing.DefaultListModel;



/**
 *
 * @author Gabriel
 */
public class vBusca extends javax.swing.JDialog {
    DefaultListModel<String> lista;
    private Object objeto_encontrado_na_busca;
    /**
     * Creates new form vProdutos
     */
    public vBusca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        lista = new DefaultListModel<>();
        Lista.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        cb_pessoa_selecionar = new javax.swing.JComboBox<>();
        but_buscar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        but_excluir = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Pesquisa:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"CPF"}));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        Lista.setVisibleRowCount(100000000);
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Lista);

        cb_pessoa_selecionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Funcionário", "Produto", "Fornecedor" }));
        cb_pessoa_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pessoa_selecionarActionPerformed(evt);
            }
        });

        but_buscar.setText("Buscar");
        but_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_buscarActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        but_excluir.setText("Excluir");
        but_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_pessoa_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addGap(29, 29, 29)
                        .addComponent(but_buscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(but_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_buscar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cb_pessoa_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(but_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
       
        
    }//GEN-LAST:event_cbTipoActionPerformed

    private void cb_pessoa_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pessoa_selecionarActionPerformed
        String pessoa = cb_pessoa_selecionar.getSelectedItem().toString();
        
        if(pessoa.equals("Cliente")){
            cbTipo.removeAllItems();
            cbTipo.addItem("CPF");
        }else if(pessoa.equals("Funcionário")){
            cbTipo.removeAllItems();
            cbTipo.addItem("CPF");
        }else if(pessoa.equals("Fornecedor")){
            cbTipo.removeAllItems();
            cbTipo.addItem("CNPJ");
        }else if(pessoa.equals("Produto")){
            cbTipo.removeAllItems();
            cbTipo.addItem("ID");
        }
    }//GEN-LAST:event_cb_pessoa_selecionarActionPerformed

    private void but_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_buscarActionPerformed

       lista.clear();
       String pesquisa = txtPesquisa.getText().trim();
       String metodo_pesquisa = cbTipo.getSelectedItem().toString();
       String tipo_pessoa = cb_pessoa_selecionar.getSelectedItem().toString();

       BuscarDAO buscar = new BuscarDAO();
       
       
    
       this.objeto_encontrado_na_busca = null; 
       
       if (tipo_pessoa.equals("Cliente") || tipo_pessoa.equals("Funcionário")) {
           ArrayList<Registro_usuario> users = buscar.Pesquisa_usuario(pesquisa, tipo_pessoa, metodo_pesquisa);
           Registro_usuario resultado_usuario = new Registro_usuario();
           for (int i = 0; i < users.size(); i++) {
               resultado_usuario = users.get(i);
               this.objeto_encontrado_na_busca = resultado_usuario; 

                if (resultado_usuario != null) {
                    lista.addElement(resultado_usuario.getNome());
                    lista.addElement("CPF: " + resultado_usuario.getCpf());
                    lista.addElement("Email: " + resultado_usuario.getEmail());
                    lista.addElement("Telefone: " + resultado_usuario.getTelefone());
                    lista.addElement("Email: " + resultado_usuario.getEmail());
                    lista.addElement("Endereço: " + resultado_usuario.getEndereco());
                    lista.addElement("Nascimento: " + resultado_usuario.getNascimento());
                    lista.addElement("");
                } else {
                    lista.addElement("Nenhum resultado encontrado.");
                }
               
           }
           

       } else if (tipo_pessoa.equals("Produto")) {
           ArrayList<Registro_produto> produto = buscar.Pesquisa_produto(pesquisa, metodo_pesquisa) ;
           Registro_produto resultado_produto = new Registro_produto();
           
           for (int i = 0; i < produto.size(); i++) {
               resultado_produto = produto.get(i);
               this.objeto_encontrado_na_busca = resultado_produto;
           
                if (resultado_produto != null) {
                    lista.addElement("ID: " + resultado_produto.getId());
                    lista.addElement(resultado_produto.getNome_produto());
                    lista.addElement("Preço: R$ " + resultado_produto.getPreco_produto());
                    lista.addElement("Qtd. em Estoque: " + resultado_produto.getQuantidade_produto());
                    lista.addElement("");
                } else {
                    lista.addElement("Nenhum resultado encontrado.");
                }

           
           }
    
           
       } else if (tipo_pessoa.equals("Fornecedor")) {
           ArrayList<Registro_fornecedor> fornecedor = buscar.Pesquisa_fornecedor(pesquisa, metodo_pesquisa);
           Registro_fornecedor resultado_fornecedor = new Registro_fornecedor();
           
           for (int i= 0; i < fornecedor.size(); i++) {
                resultado_fornecedor = fornecedor.get(i);
                this.objeto_encontrado_na_busca = resultado_fornecedor; 

                if (resultado_fornecedor != null) {
                    lista.addElement(resultado_fornecedor.getNome()); 
                    lista.addElement("CNPJ: " + resultado_fornecedor.getCnpj());
                    lista.addElement("Email: " + resultado_fornecedor.getEmail());
                    lista.addElement("Endereço: " + resultado_fornecedor.getEndereco());
                    lista.addElement("Telefone: " + resultado_fornecedor.getTelefone());
                    
                } else {
                    lista.addElement("Nenhum resultado encontrado.");
                }

               
           }
           
           
       } else {
           lista.addElement("Tipo de pesquisa não selecionado.");
       }
 
    
   
    }//GEN-LAST:event_but_buscarActionPerformed

    private void ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseClicked
       
    }//GEN-LAST:event_ListaMouseClicked

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        String pesquisa = txtPesquisa.getText().trim();
        if(pesquisa.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Pesquise especificadamente o que você deseja editar.");
            return;
        }
        if (this.objeto_encontrado_na_busca == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum item válido foi encontrado na busca.");
            return;
        }

        if (this.objeto_encontrado_na_busca instanceof Registro_usuario) {

            Registro_usuario usuario_para_editar = (Registro_usuario) this.objeto_encontrado_na_busca;    
            String tipo_pessoa_selecionado = cb_pessoa_selecionar.getSelectedItem().toString();

            vEditarBuscaClienteFuncionario tela_edicao_usuario = new vEditarBuscaClienteFuncionario(this, true, usuario_para_editar, tipo_pessoa_selecionado);
            tela_edicao_usuario.setVisible(true);
            this.but_buscar.doClick(); 
        } else if (this.objeto_encontrado_na_busca instanceof Registro_produto) {
            Registro_produto produto_para_editar = (Registro_produto) this.objeto_encontrado_na_busca;    

            vEditarBuscaProduto tela_edicao_produto = new vEditarBuscaProduto(this, true, produto_para_editar);
            tela_edicao_produto.setVisible(true);
            this.but_buscar.doClick(); 
        } else if (this.objeto_encontrado_na_busca instanceof Registro_fornecedor) {
            Registro_fornecedor fornecedor_para_editar = (Registro_fornecedor) this.objeto_encontrado_na_busca;    

            vEditarBuscaFornecedor tela_edicao_fornecedor = new vEditarBuscaFornecedor(this, true, fornecedor_para_editar);
            tela_edicao_fornecedor.setVisible(true);
            this.but_buscar.doClick();
        }
        
    }//GEN-LAST:event_EditarActionPerformed

    private void but_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_excluirActionPerformed
        String pesquisa = txtPesquisa.getText().trim();
        if(pesquisa.equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Pesquise especificadamente o que você deseja excluir.");
            return;      
        }
        if (this.objeto_encontrado_na_busca == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhum item válido foi encontrado na busca.");
            return;
        }

        int resposta = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Tem certeza que deseja excluir este registro?\nEsta ação não pode ser desfeita.",
        "Confirmação de Exclusão", 
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE
        );

 
        
        if (resposta != javax.swing.JOptionPane.YES_OPTION) {
            return; 
        }

        DAO.RegistroDAO dao = new DAO.RegistroDAO(); 
        boolean teste_excluir = false; 
        String tipo_pessoa_selecionado = cb_pessoa_selecionar.getSelectedItem().toString();



        if (this.objeto_encontrado_na_busca instanceof Registro_usuario) {

            Registro_usuario usuario = (Registro_usuario) this.objeto_encontrado_na_busca;
            teste_excluir = dao.excluir_usuario(usuario.getCpf(), tipo_pessoa_selecionado);

        } else if (this.objeto_encontrado_na_busca instanceof Registro_produto) {

            Registro_produto produto = (Registro_produto) this.objeto_encontrado_na_busca;
            teste_excluir = dao.excluir_produto(produto.getId());

        } else if (this.objeto_encontrado_na_busca instanceof Registro_fornecedor) {

            Registro_fornecedor fornecedor = (Registro_fornecedor) this.objeto_encontrado_na_busca;
            teste_excluir = dao.excluir_fornecedor(fornecedor.getCnpj());
        }

        if (teste_excluir) {
            javax.swing.JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Falha ao excluir o registro.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        this.but_buscar.doClick();
    }//GEN-LAST:event_but_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vBusca dialog = new vBusca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JList<String> Lista;
    private javax.swing.JButton but_buscar;
    private javax.swing.JButton but_excluir;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JComboBox<String> cb_pessoa_selecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
