/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visao;

import DAO.RegistroDAO;
import Modelo.Registro_fornecedor;

/**
 *
 * @author Gabriel
 */
public class vCadFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form vCadFornecedor
     */
    public vCadFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_info = new javax.swing.JPanel();
        lblnome_fornecedor = new javax.swing.JLabel();
        txtnome_fornecedor = new javax.swing.JTextField();
        lblcnpj = new javax.swing.JLabel();
        lblemail_fornecedor = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lvlendereco = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        ffCnpj = new javax.swing.JFormattedTextField();
        lbltelefone = new javax.swing.JLabel();
        txttelefone = new javax.swing.JTextField();
        painel_bot = new javax.swing.JPanel();
        butCadastrar_fornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Fornecedor");

        painel_info.setBackground(new java.awt.Color(255, 255, 255));

        lblnome_fornecedor.setText("Nome:");

        lblcnpj.setText("Cnjp:");

        lblemail_fornecedor.setText("Email:");

        lvlendereco.setText("Endereço:");

        txtendereco.setToolTipText("");

        try {
            ffCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ffCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffCnpjActionPerformed(evt);
            }
        });

        lbltelefone.setText("Telefone:");

        javax.swing.GroupLayout painel_infoLayout = new javax.swing.GroupLayout(painel_info);
        painel_info.setLayout(painel_infoLayout);
        painel_infoLayout.setHorizontalGroup(
            painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_infoLayout.createSequentialGroup()
                .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painel_infoLayout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblnome_fornecedor)
                                .addComponent(lblcnpj)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_infoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblemail_fornecedor)))
                    .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbltelefone)
                        .addComponent(lvlendereco)))
                .addGap(18, 18, 18)
                .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnome_fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(txtemail)
                    .addComponent(txtendereco)
                    .addComponent(ffCnpj)
                    .addComponent(txttelefone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_infoLayout.setVerticalGroup(
            painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_infoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnome_fornecedor)
                    .addComponent(txtnome_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcnpj)
                    .addComponent(ffCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail_fornecedor))
                .addGap(18, 18, 18)
                .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lvlendereco)
                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(painel_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelefone)
                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        butCadastrar_fornecedor.setText("Cadastrar");
        butCadastrar_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadastrar_fornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_botLayout = new javax.swing.GroupLayout(painel_bot);
        painel_bot.setLayout(painel_botLayout);
        painel_botLayout.setHorizontalGroup(
            painel_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_botLayout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(butCadastrar_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        painel_botLayout.setVerticalGroup(
            painel_botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_botLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(butCadastrar_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painel_bot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_bot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCadastrar_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadastrar_fornecedorActionPerformed
        Registro_fornecedor fornecedor = new Registro_fornecedor();
        fornecedor.setTelefone(txttelefone.getText());
        fornecedor.setNome(txtnome_fornecedor.getText());
        fornecedor.setEmail(txtemail.getText());
        fornecedor.setCnpj(ffCnpj.getText());
        fornecedor.setEndereco(txtendereco.getText());
        
        RegistroDAO registroDAO = new RegistroDAO();
        boolean salvou = registroDAO.Registrofornecedor(fornecedor);
        
        if(salvou){
            javax.swing.JOptionPane.showMessageDialog(this,"cadastro realizado");
            this.dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Email ou cnpj ja cadastrado");
        }
    }//GEN-LAST:event_butCadastrar_fornecedorActionPerformed

    private void ffCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffCnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vCadFornecedor dialog = new vCadFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCadastrar_fornecedor;
    private javax.swing.JFormattedTextField ffCnpj;
    private javax.swing.JLabel lblcnpj;
    private javax.swing.JLabel lblemail_fornecedor;
    private javax.swing.JLabel lblnome_fornecedor;
    private javax.swing.JLabel lbltelefone;
    private javax.swing.JLabel lvlendereco;
    private javax.swing.JPanel painel_bot;
    private javax.swing.JPanel painel_info;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome_fornecedor;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
