/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visao;

import Modelo.Registro_fornecedor;

/**
 *
 * @author Gabriel
 */
public class vEditarBuscaFornecedor extends javax.swing.JDialog {
    private Registro_fornecedor fornecedor_editar;
    /**
     * Creates new form vEditarBuscaFornecedor
     */
    public vEditarBuscaFornecedor(java.awt.Dialog parent, boolean modal, Registro_fornecedor fornecedor_enviado) {
        super(parent, modal);
        initComponents();
    
        this.fornecedor_editar = fornecedor_enviado;
        preencher_campos();
    }
    private void preencher_campos(){
        if(this.fornecedor_editar != null){
            txt_mudar_cnpj.setText(this.fornecedor_editar.getCnpj());
            txt_mudar_email.setText(this.fornecedor_editar.getEmail());
            txt_mudar_endereco.setText(this.fornecedor_editar.getEndereco());
            txt_mudar_nome.setText(this.fornecedor_editar.getNome());
            txt_mudar_telefone.setText(this.fornecedor_editar.getTelefone());
            
            txt_mudar_cnpj.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_cnpj = new javax.swing.JLabel();
        txt_mudar_cnpj = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_endereco = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_telefone = new javax.swing.JLabel();
        txt_mudar_email = new javax.swing.JTextField();
        txt_mudar_endereco = new javax.swing.JTextField();
        txt_mudar_nome = new javax.swing.JTextField();
        txt_mudar_telefone = new javax.swing.JTextField();
        but_confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_cnpj.setText("CNPJ:");

        lbl_email.setText("Email:");

        lbl_endereco.setText("Endereço:");

        lbl_nome.setText("Nome:");

        lbl_telefone.setText("Telefone:");

        but_confirmar.setText("Confirmar");
        but_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_telefone)
                            .addComponent(lbl_nome)
                            .addComponent(lbl_endereco)
                            .addComponent(lbl_email)
                            .addComponent(lbl_cnpj))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_mudar_cnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(txt_mudar_email)
                                .addComponent(txt_mudar_endereco))
                            .addComponent(txt_mudar_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txt_mudar_telefone)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(but_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cnpj)
                    .addComponent(txt_mudar_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_mudar_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_endereco)
                    .addComponent(txt_mudar_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome)
                    .addComponent(txt_mudar_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_telefone)
                    .addComponent(txt_mudar_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(but_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_confirmarActionPerformed
        if (txt_mudar_nome.getText().trim().isEmpty() || txt_mudar_endereco.getText().trim().isEmpty() || txt_mudar_email.getText().trim().isEmpty() || txt_mudar_telefone.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Não pode estar nada vazio");
            return; 
        }
        try {
            this.fornecedor_editar.setEmail(txt_mudar_email.getText().trim());
            this.fornecedor_editar.setEndereco(txt_mudar_endereco.getText().trim());
            this.fornecedor_editar.setNome(txt_mudar_nome.getText().trim());
            this.fornecedor_editar.setTelefone(txt_mudar_telefone.getText().trim());

            
            
            

            
            

            DAO.RegistroDAO dao_registro = new DAO.RegistroDAO(); 
            boolean deu = dao_registro.atualizar_fornecedor(fornecedor_editar);

            if (deu) {
                javax.swing.JOptionPane.showMessageDialog(this, "Fornecedor atualizado com sucesso!");
                this.dispose(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Falha ao atualizar o fornecedor no banco de dados.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
         } catch (NumberFormatException e) {
          
            javax.swing.JOptionPane.showMessageDialog(this, "Dados inseridos invalidos.", "Erro de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_but_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vEditarBuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vEditarBuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vEditarBuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vEditarBuscaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_confirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cnpj;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_mudar_cnpj;
    private javax.swing.JTextField txt_mudar_email;
    private javax.swing.JTextField txt_mudar_endereco;
    private javax.swing.JTextField txt_mudar_nome;
    private javax.swing.JTextField txt_mudar_telefone;
    // End of variables declaration//GEN-END:variables
}
