/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visao;

import Modelo.Registro_usuario;
import Modelo.Registro_usuario;
import java.text.SimpleDateFormat; // Para formatar a data
import java.text.ParseException; // Para tratar erros de data
import java.util.Date; // Para a data
/**
 *
 * @author Gabriel
 */
public class vEditarBuscaClienteFuncionario extends javax.swing.JDialog {
    private Registro_usuario usuario_para_editar;
    private String tipo_pessoa; 
    private SimpleDateFormat formatador_data = new SimpleDateFormat("yyyy-MM-dd");
/**
     * Creates new form vEditarBusca
     */
    public vEditarBuscaClienteFuncionario(java.awt.Dialog parent, boolean modal, Registro_usuario usuario_enviado, String tipo_pessoa_enviado) {
        super(parent, modal);
        initComponents();
     
        this.usuario_para_editar = usuario_enviado;
        this.tipo_pessoa = tipo_pessoa_enviado; 
        preencher_campos();
    }

 private void preencher_campos() {
        if (this.usuario_para_editar != null) {
            txt_nome_mudar.setText(this.usuario_para_editar.getNome());
            txt_cpf_mudar.setText(this.usuario_para_editar.getCpf());
            txt_email_mudar.setText(this.usuario_para_editar.getEmail());
            txt_endereco_mudar.setText(this.usuario_para_editar.getEndereco());
            txt_telefone_mudar.setText(this.usuario_para_editar.getTelefone());
            
     
            if (this.usuario_para_editar.getNascimento() != null) {
                txt_nasc_mudar.setText(formatador_data.format(this.usuario_para_editar.getNascimento()));
            }
            txt_cpf_mudar.setEnabled(false);
        }
 }
    /**ddd
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_telefone = new javax.swing.JPanel();
        txt_nome_mudar = new javax.swing.JTextField();
        txt_cpf_mudar = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email_mudar = new javax.swing.JTextField();
        txt_nasc = new javax.swing.JLabel();
        txt_nasc_mudar = new javax.swing.JTextField();
        lbl_endereco = new javax.swing.JLabel();
        txt_endereco_mudar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_telefone_mudar = new javax.swing.JTextField();
        but_confirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_telefone.setBackground(new java.awt.Color(255, 255, 255));

        txt_nome_mudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nome_mudarActionPerformed(evt);
            }
        });

        lbl_nome.setText("nome");

        jLabel1.setText("CPF:");

        lbl_email.setText("email:");

        txt_nasc.setText("Nascimento:");

        lbl_endereco.setText("Endereço");

        jLabel2.setText("Telefone: ");

        but_confirmar.setText("Confirmar mudança");
        but_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_confirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbl_telefoneLayout = new javax.swing.GroupLayout(lbl_telefone);
        lbl_telefone.setLayout(lbl_telefoneLayout);
        lbl_telefoneLayout.setHorizontalGroup(
            lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_telefoneLayout.createSequentialGroup()
                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbl_telefoneLayout.createSequentialGroup()
                        .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbl_telefoneLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_nasc)
                                    .addComponent(lbl_email)
                                    .addComponent(lbl_nome)
                                    .addComponent(jLabel1)))
                            .addGroup(lbl_telefoneLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(lbl_endereco))))
                        .addGap(28, 28, 28)
                        .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nome_mudar, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txt_cpf_mudar)
                            .addComponent(txt_email_mudar)
                            .addComponent(txt_nasc_mudar)
                            .addComponent(txt_endereco_mudar)
                            .addComponent(txt_telefone_mudar)))
                    .addGroup(lbl_telefoneLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(but_confirmar)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        lbl_telefoneLayout.setVerticalGroup(
            lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_telefoneLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome_mudar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cpf_mudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email_mudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nasc)
                    .addComponent(txt_nasc_mudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_endereco)
                    .addComponent(txt_endereco_mudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lbl_telefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_telefone_mudar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(but_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nome_mudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nome_mudarActionPerformed
        
    }//GEN-LAST:event_txt_nome_mudarActionPerformed

    private void but_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_confirmarActionPerformed
        
       
        if (txt_nome_mudar.getText().trim().isEmpty() || txt_email_mudar.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nome e Email não podem estar vazios.");
            return; 
        }
        try {
            this.usuario_para_editar.setNome(txt_nome_mudar.getText().trim());
            this.usuario_para_editar.setEmail(txt_email_mudar.getText().trim());
            this.usuario_para_editar.setEndereco(txt_endereco_mudar.getText().trim());
            this.usuario_para_editar.setTelefone(txt_telefone_mudar.getText().trim());

            
            java.util.Date data_nascimento_util = formatador_data.parse(txt_nasc_mudar.getText());//
            java.sql.Date data_nascimento_sql = new java.sql.Date(data_nascimento_util.getTime());//
            this.usuario_para_editar.setNascimento(data_nascimento_sql);// transformação data sql n mexe
    

            DAO.RegistroDAO dao_registro = new DAO.RegistroDAO(); 
            boolean deu = dao_registro.atualizar_usuario(this.usuario_para_editar, this.tipo_pessoa);

            if (deu) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
                this.dispose(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Falha ao atualizar o usuário no banco de dados.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (ParseException e) {
          
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de data inválido.", "Erro de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_but_confirmarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JPanel lbl_telefone;
    private javax.swing.JTextField txt_cpf_mudar;
    private javax.swing.JTextField txt_email_mudar;
    private javax.swing.JTextField txt_endereco_mudar;
    private javax.swing.JLabel txt_nasc;
    private javax.swing.JTextField txt_nasc_mudar;
    private javax.swing.JTextField txt_nome_mudar;
    private javax.swing.JTextField txt_telefone_mudar;
    // End of variables declaration//GEN-END:variables
}
