/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visao;

import Modelo.Registro_produto;
import java.text.ParseException;

/**
 *
 * @author Gabriel
 */
public class vEditarBuscaProduto extends javax.swing.JDialog {
     private Registro_produto produto_para_editar;
    /**
     * Creates new form vEditarBuscaProduto
     */
    public vEditarBuscaProduto(java.awt.Dialog parent, boolean modal, Registro_produto produto_enviado) {
        super(parent, modal);
        initComponents();
     
        this.produto_para_editar = produto_enviado;
        
        preencher_campos();
    }
     private void preencher_campos() {
        if (this.produto_para_editar != null) {
            txt_id.setText(String.valueOf(produto_para_editar.getId()));
            txt_mudar_nome.setText(this.produto_para_editar.getNome_produto());
            txt_mudar_preco.setText(String.valueOf(this.produto_para_editar.getPreco_produto()));
            txt_mudar_quantidade.setText(String.valueOf(this.produto_para_editar.getQuantidade_produto()));
            
            txt_id.setEnabled(false);
            
     
            
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_mudar_preco = new javax.swing.JFormattedTextField();
        lbl_preco = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        txt_mudar_nome = new javax.swing.JTextField();
        txt_mudar_quantidade = new javax.swing.JFormattedTextField();
        lbl_quantidade = new javax.swing.JLabel();
        but_confirmar = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_preco.setText("Preço:");

        lbl_nome.setText("Nome: ");

        lbl_quantidade.setText("Quantidade:");

        but_confirmar.setText("Confirmar");
        but_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_confirmarActionPerformed(evt);
            }
        });

        lbl_id.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_quantidade)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_nome)
                                    .addComponent(lbl_preco)
                                    .addComponent(lbl_id))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_mudar_quantidade)
                                    .addComponent(txt_mudar_preco)
                                    .addComponent(txt_mudar_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(but_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mudar_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_preco))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome)
                    .addComponent(txt_mudar_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mudar_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_quantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(but_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_confirmarActionPerformed
        String preco_texto = txt_mudar_preco.getText().trim();
        String quantidade_texto = txt_mudar_quantidade.getText().trim();
        
        double preco = Double.parseDouble(preco_texto);
        int quantidade = Integer.parseInt(quantidade_texto);
        if (txt_mudar_nome.getText().trim().isEmpty() || txt_mudar_preco.getText().trim().isEmpty() || txt_mudar_quantidade.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nome, preço e quantidade não pode estar vazio");
            return; 
        }
        try {
            this.produto_para_editar.setNome_produto(txt_mudar_nome.getText().trim());
            this.produto_para_editar.setPreco_produto(preco);
            this.produto_para_editar.setQuantidade_produto(quantidade);

            
            

            DAO.RegistroDAO dao_registro = new DAO.RegistroDAO(); 
            boolean deu = dao_registro.atualizar_produto(produto_para_editar);

            if (deu) {
                javax.swing.JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");
                this.dispose(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Falha ao atualizar o produto no banco de dados.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
         } catch (NumberFormatException e) {
          
            javax.swing.JOptionPane.showMessageDialog(this, "Quantidade e numeros invalidos.", "Erro de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_but_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_confirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_preco;
    private javax.swing.JLabel lbl_quantidade;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mudar_nome;
    private javax.swing.JFormattedTextField txt_mudar_preco;
    private javax.swing.JFormattedTextField txt_mudar_quantidade;
    // End of variables declaration//GEN-END:variables
}
